[project]
name = "test-uv-versioning"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "livekit",
    "python-dotenv>=1.2.1",
]
